
trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.3.0'
    checkLatest: true
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test and Coverage
  inputs:
    command: 'test'
    projects: 'NetFabric.Angle.UnitTests/NetFabric.Angle.UnitTests.csproj'    
    arguments: '/p:CollectCoverage=true /p:Exclude="[xunit.*]*" /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
    workingDirectory: 'NetFabric.Angle.UnitTests'
- task: DotNetCoreCLI@2
  displayName: Report Generator
  inputs:
    command: 'custom'
    projects: 'NetFabric.Angle.UnitTests/NetFabric.Angle.UnitTests.csproj'
    custom: 'reportgenerator'
    arguments: '-reports:$(Build.SourcesDirectory)/TestResults/Coverage/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/TestResults/Coverage/Reports'
    workingDirectory: 'NetFabric.Angle.UnitTests'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura' 
    summaryFileLocation: $(Build.SourcesDirectory)/TestResults/Coverage/**/coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)/TestResults/Coverage/Reports
